---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dapr.io/app-id: kitchen-service
    dapr.io/app-port: "8080"
    dapr.io/enabled: "true"
    dapr.io/log-level: debug
    app.quarkus.io/quarkus-version: 3.7.1
    app.quarkus.io/vcs-uri: git@github.com:mcruzdev/pizza-quarkus.git
  labels:
    app.kubernetes.io/name: pizza-kitchen
    app.kubernetes.io/managed-by: quarkus
  name: pizza-kitchen
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: pizza-kitchen
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dapr.io/app-id: kitchen-service
    dapr.io/app-port: "8080"
    dapr.io/enabled: "true"
    dapr.io/log-level: debug
    app.quarkus.io/quarkus-version: 3.7.1
    app.quarkus.io/vcs-uri: git@github.com:mcruzdev/pizza-quarkus.git
  labels:
    app.kubernetes.io/name: pizza-kitchen
    app.kubernetes.io/managed-by: quarkus
  name: pizza-kitchen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pizza-kitchen
  template:
    metadata:
      annotations:
        dapr.io/app-id: kitchen-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: debug
        app.quarkus.io/quarkus-version: 3.7.1
        app.quarkus.io/vcs-uri: git@github.com:mcruzdev/pizza-quarkus.git
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: pizza-kitchen
      namespace: default
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/matheuscruzdev/pizza-kitchen:0.0.1
          imagePullPolicy: Always
          name: pizza-kitchen
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
